In [255]:
import numpy as np
import pandas as pd
import urllib
import copy
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
import xgboost

ImportError: No module named 'xgboost'

In [228]:
data = pd.read_csv('good.csv').drop('Unnamed: 0', axis=1)

In [230]:
data.to_csv('good.csv')

In [229]:
data.head()

surname  ans lastthree lasttwo lastfour  lastthree_num  lasttwo_num  \
0     Аар    0       Аар      ар      Аар       0.000000     0.102273   
1   Аарон    0       рон      он     арон       0.227273     0.395299   
2   ААРОН    0       РОН      ОН     АРОН       0.200000     0.376623   
3  Аарона    0       она      на     рона       0.377410     0.323171   
4  Аарона    1       она      на     рона       0.377410     0.323171   

   lastfour_num  
0           0.0  
1           0.5  
2           0.0  
3           0.3  
4           0.3

In [237]:
ngram_counter = CountVectorizer(ngram_range=(1, 4), analyzer='char')

In [239]:
X_train, X_test, y_train, y_test = train_test_split(data_for_ext.drop('ans', axis=1), data_for_ext['ans'], test_size=0.33, random_state=42)

In [232]:
data_for_ext = data.drop('lasttwo', axis=1).drop('lastthree', axis=1).drop('lastfour', axis=1)

In [240]:
X_train_ext = X_train.drop('lasttwo_num', axis=1).drop('lastthree_num', axis=1).drop('lastfour_num', axis=1)
X_test_ext = X_test.drop('lasttwo_num', axis=1).drop('lastthree_num', axis=1).drop('lastfour_num', axis=1)
X_train_ext = ngram_counter.fit_transform(X_train_ext)
X_test_ext  = ngram_counter.transform(X_test_ext)

In [ ]:
X_train_final = X_train

In [252]:
X_train.drop('lasttwo_num', axis=1).drop('lastthree_num', axis=1).drop('lastfour_num', axis=1).shape

(67942, 1)

In [245]:
from scipy.sparse import csc_matrix

In [248]:
coo =X_train_ext.tocoo(copy=False)

In [250]:
pd.DataFrame({'index': coo.row, 'col': coo.col, 'data': coo.data}
                 )[['index', 'col', 'data']].sort_values(['index', 'col']
                 )

index  col  data
4       0    0     1
11      0    1     1
17      0    2     1
6       0    3     1
5       0    4     1
12      0    5     1
3       0    6     1
10      0    7     1
16      0    8     1
21      0    9     1
2       0   10     1
9       0   11     1
15      0   12     1
20      0   13     1
0       0   14     1
7       0   15     1
13      0   16     1
18      0   17     1
1       0   18     1
8       0   19     1
14      0   20     1
19      0   21     1

In [270]:
from sklearn.pipeline import Pipeline, FeatureUnion

In [ ]:
cnt1 = CountVectorizer(ngram_range=(1, 4), analyzer='char')

In [253]:
data_simple = pd.DataFrame()
data_simple['surname'] = data['surname']

In [276]:
pipeline = Pipeline([
        ('feats', FeatureUnion([("vectorizer", CountVectorizer(min_df=5, ngram_range=(1, 4), analyzer='char_wb')),
                     ("vectorizer2", TfidfVectorizer(min_df=5, analyzer='char_wb', ngram_range=(1,4)))])),
                     ("clf", SVC())
         ])

In [277]:
cross_val_score(pipeline, data['surname'], data['ans'], scoring='roc_auc')

KeyboardInterrupt: 

In [311]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000] }

In [312]:
clf = GridSearchCV(LogisticRegression(penalty='l2'), param_grid)

NameError: name 'GridSearchCV' is not defined

In [ ]:
from sklearn.mx

In [7]:
data = pd.DataFrame()
data['surname'] = raw_data['Аалтонен']
data['ans'] = raw_data[[1]]

NameError: name 'raw_data' is not defined

In [194]:
def endswith3(x):
    return x[-3:]
#     percentage =  1. * len(list(filter(lambda x: x.endswith(x[-3:]) and x[, data['surname']))
#                            / len(data.query("ans == 1")) 

def endswith2(x):
    return x[-2:]

def endswith4(x):
    return x[-4:]  

def is_in_train(x):
    return 1 if x in data['surname'] else 0

    

In [195]:
data['intrain'] = list(map(lambda x: is_in_train(x), data['surname']))
data['lastthree'] = list(map(lambda x: endswith3(x), data['surname']))
data['lasttwo'] = list(map(lambda x: endswith2(x), data['surname']))
data['lastfour'] = list(map(lambda x: endswith4(x), data['surname']))
data['stem'] = list(map(lambda x: st.stem(x), data['surname']))

In [196]:
data = copy.deepcopy(data1)


In [ ]:
train.query("lastfour == {}".format(attr, attr_value)).query('ans == 1').shape[0]

In [197]:
def process_attribute(train, attr, attr_value, attr_set):
    if attr_value in attr_set:
        return attr_set[attr_value] 
    res = train.query("{0} == \'{1}\'".format(attr, attr_value)).query('ans == 1').shape[0] * 1 / \
        train.query("{0} == \'{1}\'".format(attr, attr_value)).shape[0]
    attr_set[attr] = res
    return res

In [ ]:
# attr_set = {}
# data['lastthree_num'] = list(map(lambda x: process_attribute(data, 'lastthree', x, attr_set),\
#                       data['lastthree']))
# attr_set = {}
# data['lasttwo'] = list(map(lambda x: process_attribute(data, 'lasttwo', x, attr_set),\
#                       lasttwo_val))
attr_set = {}
data['lastfour_num'] = list(map(lambda x: process_attribute(data, 'lastfour', x, attr_set),\
                      lastfour_val))
attr_set = {}
data['stem_num'] = list(map(lambda x: process_attribute(data, 'stem', x, attr_set),\
                        stem_val))
attr_set = {}

In [315]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

ImportError: cannot import name '_safe_split'

In [ ]:
regressor = XGBRegressor(max_depth=5, n_estimators=100)
regressor .fit(data.drop['ans'], data['ans'])

In [206]:
train_data.head()

lastthree   lasttwo  lastfour      stem  y
0   0.000000  0.102273       0.0  0.000000  0
1   0.227273  0.395299       0.5  0.166667  0
2   0.200000  0.376623       0.0  0.166667  0
3   0.377410  0.323171       0.3  0.166667  0
4   0.377410  0.323171       0.3  0.166667  1

In [16]:
data = pd.read_csv('surnames_data.csv')

In [43]:
train_data = pd.DataFrame()
train_y = pd.DataFrame()
train_data['lastthree'] = data['lastthree_num']
train_data['lasttwo'] = data['lasttwo_num']
train_data['lastfour'] = data['lastfour_num']
train_data['stem'] = data['stem_num']
train_y['res'] = data['ans']

In [41]:
train_data.head()

lastthree   lasttwo  lastfour      stem  res
0   0.000000  0.102273       0.0  0.000000    0
1   0.227273  0.395299       0.5  0.166667    0
2   0.200000  0.376623       0.0  0.166667    0
3   0.377410  0.323171       0.3  0.166667    0
4   0.377410  0.323171       0.3  0.166667    1

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
lr = LogisticRegression()

In [58]:
train_data['y'] = train_y['res']

In [59]:
train_data = train_data.dropna()

In [109]:
X_train, X_test, y_train, y_test = train_test_split(train_data.drop('y', axis=1), train_data['y'], test_size=0.33, random_state=42)

In [111]:
cross_val_score(lr, X_train, y_train, scoring='roc_auc')

array([ 0.99382703,  0.99406712,  0.99370357])

In [66]:
train_data.shape

(101405, 5)

In [67]:
lr.fit(train_data.drop('y', axis=1), train_data['y'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [70]:
test = pd.read_csv('linear_test.txt')

In [85]:
from nltk.stem.snowball import RussianStemmer
st = RussianStemmer()

In [71]:
test.head()

surnames
0    Аалто
1      ААР
2     Аара
3     Ааре
4    Аарон

In [104]:
def get_corresponding(string, attr):
    try:
        res = list(data.query('{} == \'{}\''.format(attr, string))['{}_num'.format(attr)])
        if (len(res) > 0):
            return res[0]
        else:
            return 0
    except:
        return 0

In [105]:
def get_last_three(test):
    res = list(map(lambda x: x[-3:], test['surnames']))
    res = list(map(lambda x: get_corresponding(x, 'lastthree'), res))
    test['lasthree_num'] = res

In [115]:
def get_last_two():
    res = list(map(lambda x: x[-2:], test['surnames']))
    res = list(map(lambda x: get_corresponding(x, 'lasttwo'), res))
    test['lasttwo_num'] = res


In [135]:
def get_last_four():
    res = list(map(lambda x: x[-4:], test['surnames']))
    res = list(map(lambda x: get_corresponding(x, 'lastfour'), res))
    test['lastfour_num'] = res

In [120]:
def get_stem():
    res = list(map(lambda x: st.stem(x), test['surnames']))
    res = list(map(lambda x: get_corresponding(x, 'stem'), res))
    test['stem_num'] = res

In [103]:
get_last_three(test)

SyntaxError: invalid syntax (<unknown>, line 1)

In [129]:
lastthree = pd.read_csv('lastthree.csv')
lastthree = pd.read_csv('lastthree.csv')
lasttwo = pd.read_csv('lasttwo.csv')

In [132]:
test['lastthree_num'] = lastthree['lasthree_num']

In [136]:
get_last_four()

In [123]:
test['stem_num'].to_csv("stem.csv")

In [149]:
lr.fit(train_data.drop('y', axis=1).drop('stem', axis=1), train_data['y'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [150]:
result = lr.predict(test.drop('surnames',  axis=1).drop('stem_num', axis=1))

In [151]:
sample_sub = pd.read_csv('linear_ans_example.txt')

In [152]:
sample_sub['answer'] = result

In [153]:
sample_sub.to_csv('linear_ans_example.csv')

In [155]:
test['lastfour_num'].to_csv('lastfour.csv')


In [196]:
lr.fit(train_data.drop('y', axis=1).drop('stem', axis=1), train_data['y'])

TypeError: fit() got an unexpected keyword argument 'scoring'

In [278]:
result = lr3.predict_proba(test.drop('surnames',  axis=1).drop('stem_num', axis=1))

AttributeError: 'LinearSVC' object has no attribute 'predict_proba'

In [192]:
sample_sub = pd.read_csv('linear_ans_example.txt')

In [308]:
sample_sub['answer'] = result_proba

In [309]:
sample_sub = sample_sub.drop('Answer', axis=1)

In [310]:
sample_sub.to_csv('linear_ans_example_my.csv')

In [179]:
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import SGDClassifier

In [281]:
lr2 = LogisticRegression()

In [300]:
lr2.fit(train_data.drop('y', axis=1).drop('stem', axis=1), list(train_data['y']))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [301]:
result = lr2.predict_proba(test.drop('surnames',  axis=1).drop('stem_num', axis=1))

In [287]:
sample_sub = pd.read_csv('linear_ans_example.txt')


In [288]:
sample_sub['answer'] = result
sample_sub.to_csv('linear_ans_example_my.csv')

In [302]:
result = lr2.predict(test.drop('surnames',  axis=1).drop('stem_num', axis=1))
result_proba = lr2.predict_proba(test.drop('surnames',  axis=1).drop('stem_num', axis=1))

In [304]:
result_proba[result == 1]

array([[ 0.44162895,  0.55837105],
       [ 0.01041879,  0.98958121],
       [ 0.00963924,  0.99036076],
       ..., 
       [ 0.09280499,  0.90719501],
       [ 0.06720716,  0.93279284],
       [ 0.384227  ,  0.615773  ]])

In [305]:
result_proba = result_proba[:, 1]

In [307]:
result_proba[result == 1]

array([ 0.55837105,  0.98958121,  0.99036076, ...,  0.90719501,
        0.93279284,  0.615773  ])

In [279]:
lr3 = LinearSVC(probability=True)
lr3.fit(X_train.drop('stem', axis=1), y_train)

TypeError: __init__() got an unexpected keyword argument 'probability'

In [181]:
cross_val_score(lr3, train_data.drop('y', axis=1),train_data['y'], scoring='roc_auc')

array([ 0.99528177,  0.99311904,  0.99325279])

In [ ]:
lr3