# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import cross_validation, datasets

import numpy as np

/home/valeriyasin/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
from sklearn import model_selection

In [3]:
iris = datasets.load_iris()

In [4]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [5]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [6]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [7]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 7.   3.2  4.7  1.4]
 [ 7.6  3.   6.6  2.1]
 [ 6.1  2.8  4.7  1.2]
 [ 4.8  3.1  1.6  0.2]
 [ 6.8  2.8  4.8  1.4]]


Тестовая выборка:
[[ 6.5  3.   5.8  2.2]
 [ 6.4  3.1  5.5  1.8]
 [ 5.   3.5  1.6  0.6]
 [ 6.3  3.3  4.7  1.6]
 [ 4.8  3.   1.4  0.3]]


In [8]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[1 2 1 0 1 1 0 2 0 1 1 0 2 2 2 2 0 2 1 0 2 0 1 1 1 2 0 1 2 1 1 1 1 0 0 0 1
 1 1 0 0 0 1 0 0 2 2 1 1 0 0 2 2 0 0 2 0 2 2 2 2 0 2 2 0 2 2 2 2 2 1 2 0 0
 2 1 1 1 1 1 0 2 1 2 1 1 0 2 1 0 1 2 2 0 2 0 0 1 1 1 1 2 1 1 0]


Метки классов на тестовой выборке:
[2 2 0 1 0 1 2 2 0 1 1 1 2 1 2 2 1 0 2 1 0 0 0 0 0 0 2 2 2 1 2 0 2 2 0 0 0
 2 0 0 0 0 1 1 1]


### Стратегии проведения кросс-валидации

#### KFold

In [18]:

for train_indices, test_indices in model_selection.KFold(n_splits = 5,random_state=None, shuffle=False).split(np.arange(10)):
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [24]:
#многократный запуск приводит к различным разбиениям
for train_indices, test_indices in model_selection.KFold(n_splits = 2,random_state=None, shuffle=True).split(np.arange(10)):
    print train_indices, test_indices

[1 3 4 5 6] [0 2 7 8 9]
[0 2 7 8 9] [1 3 4 5 6]


In [25]:
#многократный запуск приводит к одному и  тому же разбиению, результат запуска детерминированный
for train_indices, test_indices in model_selection.KFold(n_splits = 2,random_state=1, shuffle=True).split(np.arange(10)):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [28]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in model_selection.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0).split(target, target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [29]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in model_selection.StratifiedKFold(n_splits = 2,shuffle = True).split(target, target):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[1 2 7 8] [0 3 4 5 6 9]
[0 3 4 5 6 9] [1 2 7 8]


#### ShuffleSplit

In [30]:
for train_indices, test_indices in model_selection.ShuffleSplit(n_splits=10,test_size = 0.2).split(np.arange(10)):
    print train_indices, test_indices

[3 6 7 5 4 0 9 8] [1 2]
[3 9 4 7 2 6 5 8] [1 0]
[1 4 5 9 3 8 2 7] [6 0]
[6 1 4 8 0 5 7 2] [3 9]
[1 6 2 5 3 0 7 8] [4 9]
[9 0 6 8 7 3 5 2] [1 4]
[2 5 7 1 4 8 9 6] [0 3]
[4 1 8 0 3 7 5 6] [9 2]
[4 9 0 7 6 1 3 2] [8 5]
[8 2 7 4 1 0 5 9] [3 6]


#### StratifiedShuffleSplit

In [34]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2).split(target, target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[1 5 8 3 6 2 9 0] [4 7]
[0 8 2 6 5 7 3 4] [9 1]
[9 8 5 6 0 2 1 3] [4 7]
[2 3 0 6 8 4 7 5] [1 9]


#### Leave-One-Out

In [36]:
for train_indices, test_index in model_selection.LeaveOneOut().split(np.arange(10)):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators